### ISSUE TITLE
Assignment 2 is ready for grading

### ISSUE THREAD

**Issue by gianinayumul** [VIS-2129-F2020/gyumul-vis#1]
Both the .Rmd and .html file are ready for grading.

https://vis-2129-f2020.github.io/gyumul-vis/Assignment-2.html

Thank you!

**Comment by bauranov** [comment]
Good work! Here are some comments:
- At the beginning of a code chunk add {r, message=FALSE,warning=FALSE} to suppress messages and warnings in HTML. When you knit your file, go through the HTML and see if some code chunks are displaying the text you don't want (for example when you're loading libraries or creating a cartogram). If there is such text, remove it with the code I mentioned above.
- Consider exploring more color palettes.
- You can add names of the countries with geom_label() or geom_text().
