### ISSUE TITLE
Assignment 3 is ready for grading.

### ISSUE THREAD

**Issue by gianinayumul** [VIS-2129-F2020/gyumul-vis#3]
https://vis-2129-f2020.github.io/gyumul-vis/Assignment3.html
https://vis-2129-f2020.github.io/gyumul-vis/Assignment3.rmd

**Comment by bauranov** [comment]
When choosing data to present, make sure the reader can understand what is on the map. "Point of interest" is not an informative description. Please double-check the html file before submitting and make sure there are no warnings and unnecessary messages.  Good work overall.
