### ISSUE TITLE
Assignment 4 help - 'create isochrones' won't load

### ISSUE THREAD

**Issue by gianinayumul** [VIS-2129-F2020/gyumul-vis#4]
Hello,

https://vis-2129-f2020.github.io/gyumul-vis/Assignment4.Rmd
https://vis-2129-f2020.github.io/gyumul-vis/Assignment4.html

I've tried running ines 62 - 77 in my code several times and after half an hour or more it still hasn't finished running. It corresponds to these lines in the tutorial:

```
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CPL_libraries, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = CPL_libraries, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = MA_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk)

otp_stop()
```

I've tried variables from New Orleans and San Francisco open data as well and experienced a similar load time. Everything up to this point in the tutorial worked pretty seamlessly, so I'm not sure what's going wrong.

Thanks,
Gianina

**Comment by traemalcolm** [comment]
Hi Gianina, when you're running that code you need to go down to you console tab in RStudio, and you should see the message: 

This will force Java to close, Press [enter] to continue, [escape] to abort

If you click in the console and hit your enter button, the code chunk should finish running.
